# Redfire Gateway Configuration File

[general]
node_id = "redfire-gateway-1"
description = "Redfire TDMoE to SIP Gateway"
location = "Network Operations Center"
contact = "admin@redfire-gateway.local"
max_calls = 1000
call_timeout = 300

[tdmoe]
interface = "eth0"
channels = 30
mtu = 1500
qos_dscp = 46

[e1]
interface = "span1"
framing = "crc4"
line_code = "hdb3"
clock_source = "external"
time_slots = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
channel_associated = false

[t1]
interface = "span1"
framing = "esf"
line_code = "b8zs"
clock_source = "external"
time_slots = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
channel_associated = false

[sip]
listen_port = 5060
domain = "redfire-gateway.local"
transport = "udp"
max_sessions = 500
session_timeout = 300
register_interval = 3600

[rtp]
port_range = { min = 10000, max = 20000 }
jitter_buffer_size = 50
packet_timeout = 1000

[pri]
variant = "etsi"
layer1 = "e1"
time_slots = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
switch_type = "euroISDN"
network_specific = false
point_to_point = false

[sigtran]
enabled = false
sctp_port = 2905
heartbeat_interval = 30

[sigtran.point_codes]
local = 1
remote = 2

[freetdm]
enabled = false
config_file = "/etc/freetdm.conf"
spans = []

[trunk]
trunk_type = "voice"
signaling = "pri"

[trunk.codec]
allowed_codecs = ["g711a", "g711u"]
preferred_codec = "g711a"

[trunk.codec.dtmf]
method = "rfc2833"
payload_type = 101
duration = 100
volume = -10
inter_digit_delay = 50
sip_info_content_type = "application/dtmf-relay"
redundancy = 3
end_of_event = true

[trunk.codec.dtmf.inband_frequencies]
low_freq = [697, 770, 852, 941]
high_freq = [1209, 1336, 1477, 1633]

[trunk.codec.clear_channel_config]
enabled = false
data_rate = 64000
protocol = "v110"

[nfas]
enabled = false
groups = []
switchover_timeout = 5000
heartbeat_interval = 30000
max_switchover_attempts = 3

[mobile]
enabled = false
network_type = "4g"

[mobile.msc]
address = "127.0.0.1"
port = 5060
protocol = "sip"

[mobile.codecs.amr]
enabled = false
modes = ["7.40", "12.2"]
mode_set = 0
octet_align = true
robust_sorting = false

[mobile.codecs.amr_wb]
enabled = false
modes = ["12.65", "23.85"]
mode_set = 0
octet_align = true

[mobile.codecs.evs]
enabled = false
primary_mode = 0
modes = ["9.6", "13.2"]
vbr = false

[mobile.qos]
enabled = false
conversational_class = 1
max_bitrate = 64000
guaranteed_bitrate = 64000
transfer_delay = 100
traffic_handling_priority = 1

[mobile.emergency]
enabled = true
emergency_numbers = ["112", "911"]
location_info = false

[feature_group.fgd]
enabled = false
seizure_timeout = 5000
wink_duration = 200
ani_delivery = true

[feature_group.fgb]
enabled = false
seizure_timeout = 5000
mf_signaling = true

[b2bua]
enabled = true
max_concurrent_calls = 500
call_timeout = 300
media_timeout = 60
enable_media_relay = true
enable_codec_transcoding = false  # Set to true when external transcoding library is integrated
transcoding_backend = "auto"      # cpu, simd, simd-avx2, simd-avx512, cuda, rocm, gpu, auto

# SIMD acceleration settings for codec transcoding
enable_simd = true
auto_detect_simd = true          # Auto-detect best available SIMD instruction set
simd_fallback = true            # Fallback to CPU if SIMD fails

[[b2bua.routing_table]]
id = "emergency"
pattern = "^(911|112)$"
route_type = "emergency"
target = "emergency.local"
priority = 1
codec_preference = ["g711u"]

[[b2bua.routing_table]]
id = "default"
pattern = ".*"
route_type = "direct"
target = "default.gateway.local"
priority = 100
codec_preference = ["g711a", "g711u"]

[b2bua.clustering]
enabled = false

[performance]
enabled = true
interval = 5000
history_size = 720

[performance.thresholds.cpu]
warning = 80.0
critical = 95.0

[performance.thresholds.memory]
warning = 80.0
critical = 95.0

[performance.thresholds.disk]
warning = 90.0
critical = 98.0

[performance.thresholds.load]
warning = 0.8
critical = 1.5

[performance.thresholds.network]
error_rate = 0.1
utilization_warning = 80.0

[logging]
level = "info"
file = "/var/log/redfire-gateway.log"
max_size = 104857600
max_files = 10
format = "json"

[snmp]
enabled = true
community = "public"
port = 161
bind_address = "0.0.0.0"
version = "v2c"

[testing.loopback]
enabled = true
timeout = 10000
max_concurrent = 10

[testing.bert]
enabled = true
patterns = ["prbs_15", "prbs_23"]
default_duration = 60
error_threshold = 0.001