# High Availability Clustering Configuration
# Configuration for multi-node clustered deployment
# with shared state and automatic failover

[general]
node_id = "redfire-cluster-node-01"
description = "HA Cluster Node 1 - TDMoE to SIP Gateway"
location = "Primary Data Center"
contact = "ha-team@telecom.company.com"
max_calls = 2500
call_timeout = 300

[tdmoe]
interface = "eth0"
channels = 30
mtu = 9000
qos_dscp = 46

[e1]
interface = "span1"
framing = "crc4"
line_code = "hdb3"
clock_source = "external"
time_slots = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
channel_associated = false

[sip]
listen_port = 5060
domain = "cluster.gateway.company.com"
transport = "udp"
max_sessions = 1250
session_timeout = 300
register_interval = 3600

[rtp]
port_range = { min = 20000, max = 25000 }
jitter_buffer_size = 50
packet_timeout = 1000

[trunk.codec]
allowed_codecs = ["g711a", "g711u", "g722"]
preferred_codec = "g711a"

[trunk.codec.dtmf]
method = "rfc2833"
payload_type = 101
duration = 100
volume = -10

[b2bua]
enabled = true
max_concurrent_calls = 1250
call_timeout = 300
media_timeout = 60
enable_media_relay = true
enable_codec_transcoding = false
transcoding_backend = "auto"

# Shared routing table across cluster
[[b2bua.routing_table]]
id = "emergency"
pattern = "^(911|112)$"
route_type = "emergency"
target = "emergency.psap.company.com"
priority = 1
codec_preference = ["g711u"]

[[b2bua.routing_table]]
id = "local-cluster"
pattern = "^[2-9][0-9]{3}$"
route_type = "direct"
target = "local.switch.company.com"
priority = 10
codec_preference = ["g711a", "g711u"]

[[b2bua.routing_table]]
id = "long-distance"
pattern = "^1[2-9][0-9]{9}$"
route_type = "gateway"
target = "ld.gateway.company.com"
priority = 15
codec_preference = ["g722", "g711a"]

# Clustering Configuration - Node 1
[b2bua.clustering]
enabled = true
cluster_id = "production-cluster"
node_id = "node-01"

# Anycast IP addresses shared by cluster
anycast_addresses = [
    "10.0.100.100",  # Primary service IP
    "10.0.100.101",  # Secondary service IP
]

sync_port = 8080
heartbeat_interval = 10
transaction_sync_enabled = true

# Redis cluster for shared state
shared_state_backend = { Redis = { 
    addresses = [
        "redis://10.0.100.10:6379",
        "redis://10.0.100.11:6379", 
        "redis://10.0.100.12:6379"
    ], 
    password = "cluster_redis_password" 
}}

consensus_algorithm = "raft"

# NFAS Configuration for span redundancy
[nfas]
enabled = true
switchover_timeout = 3000
heartbeat_interval = 15000
max_switchover_attempts = 5

[[nfas.groups]]
group_id = 1
primary_span = 1
backup_spans = [2]
load_balancing = true
ces = 1

# Performance monitoring for cluster
[performance]
enabled = true
interval = 5000
history_size = 720

[performance.thresholds.cpu]
warning = 75.0
critical = 90.0

[performance.thresholds.memory]
warning = 80.0
critical = 95.0

[performance.thresholds.load]
warning = 3.0
critical = 6.0

[performance.thresholds.network]
error_rate = 0.1
utilization_warning = 75.0

[logging]
level = "info"
file = "/var/log/redfire-cluster/node-01.log"
max_size = 536870912  # 512MB
max_files = 10
format = "json"

[snmp]
enabled = true
community = "cluster_monitoring"
port = 161
bind_address = "0.0.0.0"
version = "v3"

[testing]
[testing.loopback]
enabled = true
timeout = 10000
max_concurrent = 5

[testing.bert]
enabled = true
patterns = ["prbs_15", "prbs_23"]
default_duration = 120
error_threshold = 0.001

# Note: For additional cluster nodes, copy this configuration and change:
# - node_id to "node-02", "node-03", etc.
# - logging.file path
# - Any node-specific settings
# - Keep cluster_id, anycast_addresses, and shared_state_backend identical