# Production Redfire Gateway Configuration
# This configuration is suitable for production deployments
# Includes high availability, monitoring, and full feature set

[general]
node_id = "redfire-gateway-prod-01"
description = "Production TDMoE to SIP Gateway - Primary Node"
location = "Data Center Rack 42"
contact = "noc@telecom.company.com"
max_calls = 5000
call_timeout = 300

[tdmoe]
interface = "eth1"
channels = 30
mtu = 9000          # Jumbo frames for better performance
qos_dscp = 46

[e1]
interface = "span1"
framing = "crc4"
line_code = "hdb3"
clock_source = "external"
time_slots = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
channel_associated = false

[t1]
interface = "span2"
framing = "esf"
line_code = "b8zs"
clock_source = "external"
time_slots = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
channel_associated = false

[sip]
listen_port = 5060
domain = "gateway.prod.telecom.company.com"
transport = "tls"      # Use TLS for production security
max_sessions = 2500
session_timeout = 600
register_interval = 3600

[rtp]
port_range = { min = 20000, max = 30000 }
jitter_buffer_size = 100
packet_timeout = 2000

[pri]
variant = "etsi"
layer1 = "e1"
time_slots = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
switch_type = "euroISDN"
network_specific = true
point_to_point = false

[sigtran]
enabled = true
point_codes = { local = 1001, remote = 2001 }
variant = "itu"
sctp_port = 2905
heartbeat_interval = 30

[trunk]
trunk_type = "voice"
signaling = "pri"

[trunk.codec]
allowed_codecs = ["g711a", "g711u", "g722", "g729"]
preferred_codec = "g711a"

[trunk.codec.dtmf]
method = "rfc2833"
payload_type = 101
duration = 100
volume = -10
inter_digit_delay = 50
redundancy = 3
end_of_event = true

[trunk.codec.clear_channel_config]
enabled = true
data_rate = 64000
protocol = "hdlc"

[nfas]
enabled = true
switchover_timeout = 5000
heartbeat_interval = 30000
max_switchover_attempts = 3

[[nfas.groups]]
group_id = 1
primary_span = 1
backup_spans = [2, 3]
load_balancing = true
ces = 1

[mobile]
enabled = true
network_type = "volte"

[mobile.msc]
address = "10.0.1.100"
port = 5060
protocol = "sip"

[mobile.codecs.amr]
enabled = true
modes = ["7.40", "12.2"]
mode_set = 0
octet_align = true
robust_sorting = false

[mobile.codecs.amr_wb]
enabled = true
modes = ["12.65", "23.85"]
mode_set = 0
octet_align = true

[mobile.codecs.evs]
enabled = true
primary_mode = 0
modes = ["9.6", "13.2", "16.4"]
vbr = true

[mobile.qos]
enabled = true
conversational_class = 1
max_bitrate = 128000
guaranteed_bitrate = 64000
transfer_delay = 100
traffic_handling_priority = 1

[mobile.emergency]
enabled = true
emergency_numbers = ["112", "911", "999", "000"]
location_info = true

[feature_group.fgd]
enabled = true
seizure_timeout = 5000
wink_duration = 200
ani_delivery = true

[feature_group.fgb]
enabled = false
seizure_timeout = 5000
mf_signaling = true

[b2bua]
enabled = true
max_concurrent_calls = 2500
call_timeout = 600
media_timeout = 120
enable_media_relay = true
enable_codec_transcoding = true  # When external transcoding library is integrated
transcoding_backend = "auto"

# SIMD acceleration settings for high-performance codec transcoding
enable_simd = true
simd_instruction_set = "avx2"    # Force AVX2, or use "auto" for detection
auto_detect_simd = false         # Use specific instruction set above
simd_fallback = true            # Fallback to CPU if SIMD fails

# Production routing rules
[[b2bua.routing_table]]
id = "emergency-911"
pattern = "^911$"
route_type = "emergency"
target = "911.psap.state.gov"
priority = 1
codec_preference = ["g711u"]

[[b2bua.routing_table]]
id = "emergency-112"
pattern = "^112$"
route_type = "emergency"
target = "112.emergency.eu"
priority = 1
codec_preference = ["g711a"]

[[b2bua.routing_table]]
id = "international"
pattern = "^011[0-9]+"
route_type = "gateway"
target = "international.gateway.company.com"
priority = 5
codec_preference = ["g729", "g711a"]

[b2bua.routing_table.translation]
prefix_strip = "011"
prefix_add = "+"

[[b2bua.routing_table]]
id = "national"
pattern = "^1[2-9][0-9]{9}$"
route_type = "gateway"
target = "national.gateway.company.com"
priority = 10
codec_preference = ["g711u", "g722"]

[[b2bua.routing_table]]
id = "local"
pattern = "^[2-9][0-9]{6}$"
route_type = "direct"
target = "local.switch.company.com"
priority = 15
codec_preference = ["g711a", "g711u"]

[b2bua.clustering]
enabled = true
cluster_id = "prod-cluster-01"
node_id = "node-01"
anycast_addresses = ["10.0.1.200", "10.0.1.201"]
sync_port = 8080
heartbeat_interval = 30
transaction_sync_enabled = true
shared_state_backend = { Redis = { addresses = ["redis://10.0.1.50:6379", "redis://10.0.1.51:6379"], password = "secure_password_here" } }
consensus_algorithm = "raft"

[performance]
enabled = true
interval = 5000
history_size = 720

[performance.thresholds.cpu]
warning = 80.0
critical = 95.0

[performance.thresholds.memory]
warning = 80.0
critical = 95.0

[performance.thresholds.disk]
warning = 90.0
critical = 98.0

[performance.thresholds.load]
warning = 4.0
critical = 8.0

[performance.thresholds.network]
error_rate = 0.1
utilization_warning = 80.0

[logging]
level = "info"
file = "/var/log/redfire-gateway/gateway.log"
max_size = 1073741824  # 1GB
max_files = 20
format = "json"

[snmp]
enabled = true
community = "prod_readonly_community"
port = 161
bind_address = "0.0.0.0"
version = "v3"

[testing]
[testing.loopback]
enabled = true
timeout = 10000
max_concurrent = 10

[testing.bert]
enabled = true
patterns = ["prbs_15", "prbs_23", "qrss"]
default_duration = 300
error_threshold = 0.0001